### ISSUE TITLE
Make Azure Service and VMEnv handle multi-VM scenarios

### ISSUE THREAD

**Issue by motus** [microsoft/MLOS#373]
To that end, we have to:
* Move parameters like `deploymentTemplatePath`, `deploymentName`, `resourceGroup` from service to the environment configuration
* Pass the required parameters into the service calls like `.vm_provision()`, `vm_start()`, and `remote_exec()`
* Propagate common config parameters from composite environments down to its children

**Comment by bpkroth** [comment]
Per discussion elsewhere, I think several of those should remain in the Service and we can instead of have a Service-mixin stack associated with a particular CompositeEnv stack so that Service configs are still separated that way.
Things like resourceGroup can get moved to global_config.jsonc files since they're really a sort of privilege control anyways.

**Comment by bpkroth** [comment]
#375 and #377 are addressing some of this.

**Comment by bpkroth** [comment]
@motus is this done?

**Comment by motus** [comment]
yes, I think we can close this one
